version: 0.2
phases:
  install:
    commands:
      - echo Package install started on `date`
      - gem update bundler
      - bundle install
  pre_build:
    commands:
      - echo Pre build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - jekyll build
  post_build:
    commands:
      - echo Post build started on `date`
      - aws s3 sync --delete ./_site s3://$S3_BUCKET_WEBSITE/
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
cache:
  paths:
    - '/usr/local/bundle/**/*'
